DROP TABLE MVC_MEMBER;
CREATE TABLE MVC_MEMBER(
    mID VARCHAR2(30) PRIMARY KEY,
    mPW VARCHAR2(30) NOT NULL,
    mNAME VARCHAR2(30) NOT NULL,
    mEMAIL VARCHAR2(30),
    mPHOTO VARCHAR2(30) DEFAULT 'NOIMG.jpg' NOT NULL,
    mBIRTH DATE,
    mADDRESS VARCHAR2(300),
    mRDATE DATE DEFAULT SYSDATE NOT NULL
);

-- DUMMY DATA
SELECT * FROM MVC_MEMBER;
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
    VALUES ('aaa', '111', '홍준표', 'hong@strength.com', '1958-05-05', '대구광역시');
-- DAO에 들어갈 QUERY

    -- 1. ID 중복 체크
    SELECT COUNT(*) FROM MVC_MEMBER WHERE MID='aaa';
    -- 2. JOIN 
    INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS)
    VALUES ('sss', '333', '산삼이', 'sansam@mountain.com', DEFAULT, '1111-01-01', '백두산');
    -- 3. LOGIN CHECK
    SELECT * FROM MVC_MEMBER WHERE MID='sss' AND MPW='333';
    -- 4. mID로 MemberDto 가져오기
    SELECT * FROM MVC_MEMBER WHERE MID='sss';
    
COMMIT;