-- 프로그램 요구사항에 필요한 DML

-- 기능별 query 작성 (1, 2, 3)

-- 그냥 SELECT
SELECT pNO, pNAME, P.jNO, KOR, ENG, MAT
    FROM PERSON P, JOB J
    WHERE P.jNO=J.jNO;
SELECT JNAME FROM JOB;

-- 1
INSERT INTO PERSON VALUES(TO_CHAR(PERSON_NO_SQ.NEXTVAL), '이상해씨', (SELECT JNO FROM JOB WHERE JNAME='가수'), 90, 80, 81 );

-- 2     
SELECT ROWNUM RANK, A.*
  FROM (SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
            FROM PERSON P, JOB J
            WHERE P.JNO=J.JNO AND JNAME='배우'
            ORDER BY SUM DESC) A;

-- 3
SELECT ROWNUM RANK, A.*
  FROM (SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
            FROM PERSON P, JOB J
            WHERE P.JNO=J.JNO
            ORDER BY SUM DESC) A;