-- [ VIII ] SEQUENCE : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 안 쓰면 1부터
    INCREMENT BY 1 -- 안 쓰면 1씩 증가
    MAXVALUE 9999 -- 최대값, 꼭 씀.
    MINVALUE 1    -- 최소값
    NOCACHE
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 시퀀스의 현재 값
DROP SEQUENCE FRIEND_SEQ;
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 9999 NOCACHE NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY, -- 시퀀스 이용
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE, -- UNIQUE: 유일, NULL 허용
    ADDRESS VARCHAR2(250),
    LAST_MOODIFIED DATE DEFAULT SYSDATE -- 최종 수정일
);
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '서울시 서대문구'); -- 몇번이고 가능
-- INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
--     VALUES (FRIEND_SQ.NEXTVAL, NULL, '010-9999-9999', '서울시 마포구'); -- 에러(UNIQUE)
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SQ.NEXTVAL, '김길동', '010-9999-9999', '서울시 마포구');
SELECT * FROM FRIEND;
    -- ex. 초기값 101부터 최대값 999,999까지 1씩 증가하는 TEST_SEQ 시퀀스를 생성하고 시퀀스 수를 사용하시오
CREATE SEQUENCE TEST_SEQ 
    START WITH 101 
    MAXVALUE 999999 
    NOCACHE 
    NOCYCLE;
SELECT TEST_SEQ.NEXTVAL FROM DUAL;
SELECT TEST_SEQ.CURRVAL FROM DUAL;