DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

CREATE TABLE MEMBER_LEVEL (
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(30) NOT NULL
);

CREATE TABLE MEMBER(
    MNO     NUMBER(4) PRIMARY KEY,
    MNAME   VARCHAR2(30) NOT NULL,
    MPW     VARCHAR2(30) CHECK (1<=LENGTH(mPW) AND LENGTH(mPW)<=8),
    MEMAIL  VARCHAR2(30) UNIQUE,
    MPOINT  NUMBER(10) CHECK (MPOINT>=0),
    MRDATE  DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(2) REFERENCES MEMBER_LEVEL(LEVELNO)
);

DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCACHE
    NOCYCLE;

INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0, 'ÀÏ¹Ý');
INSERT INTO MEMBER_LEVEL VALUES (1, '½Ç¹ö');
INSERT INTO MEMBER_LEVEL VALUES (2, '°ñµå');

INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, 'È«±æµ¿', 'aa', 'hong@hong.com', 0, '22/03/10', 0);
INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, '½Å±æµ¿', 'bb', 'sin@sin.com', 1000, '22/04/01', 1);

select MNO, MNAME, MRDATE, MEMAIL mMAIL, MPOINT point, LEVELNAME || '°í°´' "LEVELNAME"
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO=L.LEVELNO;