-- ex1
INSERT INTO DEPT VALUES (50, 'IT', 'SEOUL');
COMMIT;
-- ex2
INSERT INTO DEPT VALUES (50, 'IT', 'SEOUL');
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO=50;

-- update
UPDATE DEPT SET DNAME='MARKETING', LOC='SWEDEN'
    WHERE DEPTNO=52;
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO=50;
SELECT * FROM DEPT;
COMMIT;

-- delete
DELETE FROM DEPT WHERE DEPTNO=50;
COMMIT;

-- INSERT (COM.LEC.EX6)
-- (사번,이름, 상사이름, 급여, 급여등급, 상사가 없는 사람은 CEO라고 출력)
SELECT W.EMPNO, W.ENAME, NVL(M.ENAME,'CEO') MANAGER, W.SAL, GRADE
    FROM EMP W, EMP M, DEPT D, SALGRADE
    WHERE W.MGR=M.EMPNO AND W.DEPTNO=D.DEPTNO 
        AND W.SAL BETWEEN LOSAL AND HISAL
        AND DNAME=UPPER('SALES');