-- 0. 레벨 이름들 검색
SELECT LEVELNAME FROM cLEVEL;

-- 1. 회원가입(고객 전화와 고객 이름은 입력받아 INSERT)
INSERT INTO CUSTOMER VALUES(TO_CHAR(CUSTOMER_ID_SQ.NEXTVAL), '010-9999-9999', '홍길동', DEFAULT, DEFAULT, DEFAULT);

-- 2. 핸드폰 뒷4자리(FULL) 검색 - CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업에 남은 금액
SELECT CTEL, CNAME, CPOINT, CAMOUNT, C.LEVELNAME, (SELECT MAX_NEED-CAMOUNT FROM CUSTOMER, CLEVEL
    WHERE CAMOUNT BETWEEN MIN_NEED AND MAX_NEED)NEEDAMOUNT FROM CUSTOMER C, CLEVEL L
    WHERE CAMOUNT BETWEEN MIN_NEED AND MAX_NEED
        AND SUBSTR(CTEL, -4, 4)=9999;
-- 레벨업에 남은 금액
        SELECT MAX_NEED-CAMOUNT NEEDAMOUNT FROM CUSTOMER, CLEVEL
            WHERE CAMOUNT BETWEEN MIN_NEED AND MAX_NEED;
    
-- 3. 물품 구매
UPDATE CUSTOMER SET CAMOUNT= CAMOUNT+1000000, CPOINT = CPOINT+0.05*1000000
    WHERE SUBSTR(CTEL, -4, 4)=9999 AND CNAME='홍길동';
UPDATE CUSTOMER SET LEVELNO= LEVELNO+1; ------------------------------------------------------------------------------------------------------------------

-- 4. 등급별출력 ? CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을위한쓸돈
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, C.LEVELNAME, (SELECT MAX_NEED-CAMOUNT FROM CUSTOMER, CLEVEL
        WHERE CAMOUNT BETWEEN MIN_NEED AND MAX_NEED)NEEDAMOUNT FROM CUSTOMER C, CLEVEL L
    WHERE CAMOUNT BETWEEN MIN_NEED AND MAX_NEED
    ORDER BY CAMOUNT;

-- 5. 전체출력 ? CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 레벨업을위한쓸돈
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, C.LEVELNAME, (SELECT MAX_NEED-CAMOUNT FROM CUSTOMER, CLEVEL
        WHERE CAMOUNT BETWEEN MIN_NEED AND MAX_NEED)NEEDAMOUNT FROM CUSTOMER C, CLEVEL L
    WHERE CAMOUNT BETWEEN MIN_NEED AND MAX_NEED;

-- 6. 회원탈퇴
DELETE FROM CUSTOMER 
    WHERE SUBSTR(CTEL, -4, 4)=9999 AND CNAME='홍길동';


