-- 테이블 생성 & 더미 데이터

-- 테이블 및 시퀀스 삭제
DROP TABLE CUSTOMER;
DROP TABLE cLEVEL;
DROP SEQUENCE CUSTOMER_ID_SQ;
-- 테이블 및 시퀀스 생성
CREATE TABLE cLEVEL (
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(50),
    MIN_NEED NUMBER(9),
    MAX_NEED NUMBER(9)
);
CREATE TABLE CUSTOMER (
    cID NUMBER(5) PRIMARY KEY,
    cTEL VARCHAR2(50) NOT NULL,
    cNAME VARCHAR2(50) NOT NULL,
    cPOINT NUMBER(8) DEFAULT 1000,
    cAMOUNT NUMBER(9) DEFAULT 0,
    LEVELNO NUMBER(2) DEFAULT 0 REFERENCES cLEVEL(LEVELNO)
);
CREATE SEQUENCE CUSTOMER_ID_SQ MAXVALUE 99999 NOCACHE NOCYCLE;
-- 더미데이터 insert
INSERT INTO cLEVEL VALUES(0, '일반고객', 0, 200000);
INSERT INTO cLEVEL VALUES(1, '우수고객', 200001, 1000000);
INSERT INTO cLEVEL VALUES(2, 'VIP', 1000001, 999999999);

INSERT INTO CUSTOMER VALUES(TO_CHAR(CUSTOMER_ID_SQ.NEXTVAL), '010-9999-9999', '홍길동', DEFAULT, DEFAULT, DEFAULT);

COMMIT;